apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-lb
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.fn_lb.replicas }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
       labels:
         app: {{ template "fullname" . }}
         chart: {{ .Chart.Name }}-{{ .Chart.Version }}
         heritage: {{ .Release.Service }}
         release: {{ .Release.Name }}
         role: fn-service
       annotations:
         prometheus.io/scrape: 'true'
         prometheus.io/port: {{ .Values.fn_lb.service.port | quote }}
         prometheus.io/path: '/metrics'
    spec:
      {{- if .Values.fn_lb.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.fn_lb.nodeSelector | indent 8 }}
{{- end }}
      {{- if .Values.fn_lb.tolerations }}
      tolerations:
{{ toYaml .Values.fn_lb.tolerations | indent 8 }}
{{- end }}
      containers:
        - name: runner-lb
          image: {{ .Values.fn_lb.image }}:{{ .Values.fn_lb.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
{{ toYaml .Values.fn_lb.resources | indent 12 }}
          securityContext:
            privileged: true
          ports:
          - containerPort: {{ .Values.fn_lb.service.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.fn_lb.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
          - name: FN_LOG_LEVEL
            value: {{ .Values.logLevel.fn | quote }}
        {{- if eq .Values.logLevel.fn "debug" }}
          - name: GIN_MODE
            value: "debug"
        {{- end }}
          - name: FN_GRPC_PORT
            value: {{ .Values.fn_runner.service.grpc_port | quote }}
          - name: FN_PORT
            value: {{ .Values.fn_lb.service.port | quote }}
          - name: FN_RUNNER_API_URL
            value: {{ template "mu.private_api_url" . }}
          - name: FN_RUNNER_K8S_HEADLESS_SERVICE
            value: {{ template "fullname" . }}-runner-headless
          {{- range $key, $value := .Values.fn_lb.env }}
            {{- if $value }}
          - name: {{ $key }}
            value: {{ $value | quote }}
            {{- end }}
          {{- end }}
