apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
       labels:
         app: {{ template "fullname" . }}
         chart: {{ .Chart.Name }}-{{ .Chart.Version }}
         heritage: {{ .Release.Service }}
         release: {{ .Release.Name }}
         role: fn-service
    spec:
      {{- if .Values.rbac }}
      serviceAccountName: {{ .Release.Name }}-service-account
      {{- end }}
      {{- if .Values.fn_api.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.fn_api.nodeSelector | indent 8 }}
{{- end }}
      {{- if .Values.fn_api.tolerations }}
      tolerations:
{{ toYaml .Values.fn_api.tolerations | indent 8 }}
{{- end }}
      containers:
        - name: api
          image: {{ .Values.fn_api.image }}:{{ .Values.fn_api.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
{{ toYaml .Values.fn_api.resources | indent 12 }}
          securityContext:
            privileged: true
          ports:
          - containerPort: {{ .Values.fn_api.service.port }}
          readinessProbe:
            httpGet:
              path: /v2/apps
              port: {{ .Values.fn_api.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
          - name: FN_LOG_LEVEL
            value: {{ .Values.logLevel.api | quote }}
        {{- if eq .Values.logLevel.api "debug" }}
          - name: GIN_MODE
            value: "debug"
        {{- end }}
          - name: FN_PORT
            value: {{ .Values.fn_api.service.port | quote }}
          - name: FN_PUBLIC_LB_URL
            value: {{ template "mu.public.fn.url" . }}
          - name: FN_DB_URL
            value: {{ template "mu.private_mysql_url" . }}
          {{- range $key, $value := .Values.fn_api.env }}
            {{- if $value }}
          - name: {{ $key }}
            value: {{ $value | quote }}
            {{- end }}
          {{- end }}
        - name: runner-lb
          image: {{ .Values.fn_lb.image }}:{{ .Values.fn_lb.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
{{ toYaml .Values.fn_lb.resources | indent 12 }}
          securityContext:
            privileged: true
          ports:
          - containerPort: {{ .Values.fn_lb.service.port }}
          env:
          - name: FN_LOG_LEVEL
            value: {{ .Values.logLevel.fn | quote }}
        {{- if eq .Values.logLevel.fn "debug" }}
          - name: GIN_MODE
            value: "debug"
        {{- end }}
          - name: FN_GRPC_PORT
            value: {{ .Values.fn_runner.service.grpc_port | quote }}
          - name: FN_PORT
            value: {{ .Values.fn_lb.service.port | quote }}
          - name: FN_RUNNER_API_URL
            value: {{ template "mu.private_api_url" . }}
          - name: FN_RUNNER_K8S_HEADLESS_SERVICE
            value: {{ template "fullname" . }}-runner-headless
          {{- range $key, $value := .Values.fn_lb.env }}
            {{- if $value }}
          - name: {{ $key }}
            value: {{ $value | quote }}
            {{- end }}
          {{- end }}
