apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-api
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: api
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.fn_api.replicas }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      component: api
  template:
    metadata:
       labels:
         app: {{ template "fullname" . }}
         chart: {{ .Chart.Name }}-{{ .Chart.Version }}
         heritage: {{ .Release.Service }}
         release: {{ .Release.Name }}
         component: api
         role: fn-service
       annotations:
         prometheus.io/scrape: 'true'
         prometheus.io/port: {{ .Values.fn_api.service.port | quote }}
         prometheus.io/path: '/metrics'
    spec:
      {{- if .Values.fn_api.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.fn_api.nodeSelector | indent 8 }}
{{- end }}
      {{- if .Values.fn_api.tolerations }}
      tolerations:
{{ toYaml .Values.fn_api.tolerations | indent 8 }}
{{- end }}
      containers:
        - name: api
          image: {{ .Values.fn_api.image }}:{{ .Values.fn_api.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
{{ toYaml .Values.fn_api.resources | indent 12 }}
          securityContext:
            privileged: true
          ports:
          - containerPort: {{ .Values.fn_api.service.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.fn_api.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v2/apps
              port: {{ .Values.fn_api.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
          env:
          - name: FN_LOG_LEVEL
            value: {{ .Values.logLevel.api | quote }}
        {{- if eq .Values.logLevel.api "debug" }}
          - name: GIN_MODE
            value: "debug"
        {{- end }}
          - name: FN_PORT
            value: {{ .Values.fn_api.service.port | quote }}
          - name: FN_PUBLIC_LB_URL
            value: {{ template "mu.public.fn.url" . }}
          - name: FN_DB_URL
            value: {{ template "mu.private_mysql_url" . }}
          {{- range $key, $value := .Values.fn_api.env }}
            {{- if $value }}
          - name: {{ $key }}
            value: {{ $value | quote }}
            {{- end }}
          {{- end }}
