apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-lb
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: lb
  namespace: {{ .Release.Namespace | quote }}
{{- if .Values.fn_lb.service.annotations }}
  annotations:
{{ toYaml .Values.fn_lb.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.fn_lb.service.type }}
  ports:
  - name: api
    port: {{ .Values.fn_lb.service.port }}
    targetPort: {{ .Values.fn_lb.service.port }}
  selector:
    app: {{ template "fullname" . }}
    component: lb
    role: fn-service
