{{- if .Values.fn_flow.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-flow
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
{{- if .Values.fn_flow.service.annotations }}
  annotations:
{{ toYaml .Values.fn_flow.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.fn_flow.service.type }}
  ports:
    - name: flow
      port: {{ .Values.fn_flow.service.port }}
      targetPort: 8081
  selector:
    app: {{ template "fullname" . }}
    role: flow
{{- end }}