{{- if .Values.fn_flow.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-flow-depl
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: step
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      component: step
  template:
    metadata:
       labels:
         app: {{ template "fullname" . }}
         chart: {{ .Chart.Name }}-{{ .Chart.Version }}
         heritage: {{ .Release.Service }}
         release: {{ .Release.Name }}
         component: step
         role: flow
    spec:
      containers:
        - name: flow
          image: {{ .Values.fn_flow.image }}:{{ .Values.fn_flow.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
{{ toYaml .Values.fn_flow.resources | indent 12 }}
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /ping
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 20
          env:
          - name: LOG_LEVEL
            value: {{ .Values.logLevel.flow | quote }}
          - name: LISTEN
            value: :8081
          - name: DB_PASSWD
            value: boomsauce
          - name: DB_HOST
            value: {{ .Release.Name }}-mysql
          - name: DB_URL
            value: mysql://fnapp:$(DB_PASSWD)@tcp($(DB_HOST):3306)/fndb
          - name: API_URL
            value: http://{{ template "fullname" . }}-api
{{- end }}